package tech.lucam.composeum.ksp.codegen

import tech.lucam.composeum.ksp.model.ParamModel
import tech.lucam.composeum.ksp.model.PreviewModel
import tech.lucam.composeum.ksp.model.SealedSubtype
import com.google.devtools.ksp.processing.CodeGenerator
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.UNIT
import com.squareup.kotlinpoet.buildCodeBlock
import com.squareup.kotlinpoet.ksp.writeTo

internal object ParamFormGenerator {

    private val composableClass = ClassName("androidx.compose.runtime", "Composable")
    private val previewParamStateClass = ClassName("tech.lucam.composeum.runtime", "PreviewParamState")
    private val colorClass = ClassName("androidx.compose.ui.graphics", "Color")
    private val dpClass = ClassName("androidx.compose.ui.unit", "Dp")
    private val textUnitClass = ClassName("androidx.compose.ui.unit", "TextUnit")
    private val textUnitTypeClass = ClassName("androidx.compose.ui.unit", "TextUnitType")
    private val modifierClass = ClassName("androidx.compose.ui", "Modifier")
    private val fillMaxWidthMember = MemberName("androidx.compose.foundation.layout", "fillMaxWidth")
    private val paddingMember = MemberName("androidx.compose.foundation.layout", "padding")
    private val dpMember = MemberName("androidx.compose.ui.unit", "dp")
    private const val WIDGETS_PACKAGE = "tech.lucam.composeum.runtime.ui.widgets"

    fun generate(model: PreviewModel, codeGenerator: CodeGenerator, registryPackage: String) {
        if (model.params.isEmpty()) return

        val formFunctionName = "${model.functionSimpleName}ParamForm"

        val onUpdateType = LambdaTypeName.get(
            parameters = arrayOf(previewParamStateClass),
            returnType = UNIT,
        )

        val funcSpec = FunSpec.builder(formFunctionName)
            .addModifiers(KModifier.INTERNAL)
            .addAnnotation(composableClass)
            .addParameter("state", previewParamStateClass)
            .addParameter("onUpdate", onUpdateType)
            .addCode(buildBody(model.params))
            .build()

        FileSpec.builder(registryPackage, formFunctionName)
            .addFileComment("DO NOT EDIT — generated by compose-preview KSP processor")
            .addFunction(funcSpec)
            .build()
            .writeTo(codeGenerator, aggregating = false)
    }

    private fun buildBody(params: List<ParamModel>): CodeBlock = buildCodeBlock {
        for (param in params) {
            add(buildWidgetCall(param))
        }
    }

    // ── top-level dispatch ─────────────────────────────────────────────────────

    private fun buildWidgetCall(param: ParamModel): CodeBlock = when {
        param.isNullable -> buildNullableCall(param)
        param.isList -> buildListCall(param)
        param.isDataClass -> buildDataClassSection(param)
        param.isSealedClass -> buildSealedClassSection(param)
        param.options.isNotEmpty() || param.isEnum -> buildDropdownCall(param)
        else -> buildTypedFieldCall(param)
    }

    // ── nullable wrapper ───────────────────────────────────────────────────────

    private fun buildNullableCall(param: ParamModel): CodeBlock {
        val isNullKey = "${param.name}#isNull"
        val defaultIsNull = param.defaultValue.isEmpty() || param.defaultValue == "null"
        val inner = buildWidgetCall(param.copy(isNullable = false))
        return buildCodeBlock {
            add("%M(\n", MemberName(WIDGETS_PACKAGE, "PreviewNullableWrapper"))
            indent()
            addStatement("label = %S,", param.label)
            add("isNull = state[%S] ?: %L,\n", isNullKey, defaultIsNull)
            add("onNullChange = { onUpdate(state.put(%S, it)) },\n", isNullKey)
            if (param.description.isNotEmpty()) addStatement("description = %S,", param.description)
            unindent()
            add(") {\n")
            indent()
            add(inner)
            unindent()
            add("}\n")
        }
    }

    // ── list ──────────────────────────────────────────────────────────────────

    private fun buildListCall(param: ParamModel): CodeBlock {
        val countKey = "${param.name}#count"
        val prefix = "${param.name}#"
        val countVar = "_${param.name}_count"
        return buildCodeBlock {
            add("val %L = state.get<Int>(%S) ?: 0\n", countVar, countKey)
            add("%M(\n", MemberName(WIDGETS_PACKAGE, "PreviewListField"))
            indent()
            addStatement("label = %S,", param.label)
            add("itemCount = %L,\n", countVar)
            add("onAdd = { onUpdate(state.put(%S, %L + 1)) },\n", countKey, countVar)
            add("onRemove = { _idx ->\n")
            indent()
            add("var _s = state\n")
            add("for (_i in _idx until (%L - 1)) {\n", countVar)
            indent()
            add("_s = _s.put(%S + _i.toString(), %L)\n",
                prefix, listItemReadExpr(param, prefix, "(_i + 1)"))
            unindent()
            add("}\n")
            add("onUpdate(_s.put(%S, (%L - 1).coerceAtLeast(0)))\n", countKey, countVar)
            unindent()
            add("},\n")
            if (param.description.isNotEmpty()) addStatement("description = %S,", param.description)
            unindent()
            add(") { _idx ->\n")
            indent()
            add(buildListItemWidget(param, prefix))
            unindent()
            add("}\n")
        }
    }

    /** Generates an expression that reads one list item from state. [indexExpr] is a code expression. */
    private fun listItemReadExpr(param: ParamModel, prefix: String, indexExpr: String): CodeBlock =
        when (param.listElementKotlinType) {
            "kotlin.String"  -> buildCodeBlock {
                add("state.get<String>(%S + %L.toString()) ?: %S", prefix, indexExpr, "")
            }
            "kotlin.Int"     -> buildCodeBlock { add("state.get<Int>(%S + %L.toString()) ?: 0", prefix, indexExpr) }
            "kotlin.Long"    -> buildCodeBlock { add("state.get<Long>(%S + %L.toString()) ?: 0L", prefix, indexExpr) }
            "kotlin.Float"   -> buildCodeBlock { add("state.get<Float>(%S + %L.toString()) ?: 0f", prefix, indexExpr) }
            "kotlin.Double"  -> buildCodeBlock { add("state.get<Double>(%S + %L.toString()) ?: 0.0", prefix, indexExpr) }
            "kotlin.Boolean" -> buildCodeBlock { add("state.get<Boolean>(%S + %L.toString()) ?: false", prefix, indexExpr) }
            else             -> buildCodeBlock {
                add("state.get<String>(%S + %L.toString()) ?: %S", prefix, indexExpr, "")
            }
        }

    private fun buildListItemWidget(param: ParamModel, prefix: String): CodeBlock = when {
        param.listElementIsEnum -> buildCodeBlock {
            add("%M(\n", MemberName(WIDGETS_PACKAGE, "PreviewDropdownField"))
            indent()
            add("label = \"[\${_idx + 1}]\",\n")
            add("value = state.get<String>(%S + _idx.toString()) ?: %S,\n",
                prefix, param.listElementEnumValues.firstOrNull() ?: "")
            add("options = listOf(")
            param.listElementEnumValues.forEachIndexed { i, v -> if (i > 0) add(", "); add("%S", v) }
            add("),\n")
            add("onValue = { onUpdate(state.put(%S + _idx.toString(), it)) },\n", prefix)
            unindent()
            add(")\n")
        }
        param.listElementKotlinType == "kotlin.String" -> buildCodeBlock {
            add("%M(\n", MemberName(WIDGETS_PACKAGE, "PreviewStringField"))
            indent()
            add("label = \"[\${_idx + 1}]\",\n")
            add("value = state.get<String>(%S + _idx.toString()) ?: %S,\n", prefix, "")
            add("onValue = { onUpdate(state.put(%S + _idx.toString(), it)) },\n", prefix)
            unindent()
            add(")\n")
        }
        param.listElementKotlinType == "kotlin.Boolean" -> buildCodeBlock {
            add("%M(\n", MemberName(WIDGETS_PACKAGE, "PreviewBooleanField"))
            indent()
            add("label = \"[\${_idx + 1}]\",\n")
            add("value = state.get<Boolean>(%S + _idx.toString()) ?: false,\n", prefix)
            add("onValue = { onUpdate(state.put(%S + _idx.toString(), it)) },\n", prefix)
            unindent()
            add(")\n")
        }
        param.listElementKotlinType == "kotlin.Int" ||
        param.listElementKotlinType == "kotlin.Long" -> buildCodeBlock {
            add("%M(\n", MemberName(WIDGETS_PACKAGE, "PreviewIntField"))
            indent()
            add("label = \"[\${_idx + 1}]\",\n")
            add("value = state.get<Int>(%S + _idx.toString()) ?: 0,\n", prefix)
            add("onValue = { onUpdate(state.put(%S + _idx.toString(), it)) },\n", prefix)
            unindent()
            add(")\n")
        }
        param.listElementKotlinType == "kotlin.Float" ||
        param.listElementKotlinType == "kotlin.Double" -> buildCodeBlock {
            add("%M(\n", MemberName(WIDGETS_PACKAGE, "PreviewFloatField"))
            indent()
            add("label = \"[\${_idx + 1}]\",\n")
            add("value = state.get<Float>(%S + _idx.toString()) ?: 0f,\n", prefix)
            add("onValue = { onUpdate(state.put(%S + _idx.toString(), it)) },\n", prefix)
            unindent()
            add(")\n")
        }
        else -> buildCodeBlock {
            // Fallback: string field
            add("%M(\n", MemberName(WIDGETS_PACKAGE, "PreviewStringField"))
            indent()
            add("label = \"[\${_idx + 1}]\",\n")
            add("value = state.get<String>(%S + _idx.toString()) ?: %S,\n", prefix, "")
            add("onValue = { onUpdate(state.put(%S + _idx.toString(), it)) },\n", prefix)
            unindent()
            add(")\n")
        }
    }

    // ── data class ────────────────────────────────────────────────────────────

    private fun buildDataClassSection(param: ParamModel): CodeBlock = buildCodeBlock {
        // Section header label
        add("%M(\n", MemberName("androidx.compose.material3", "Text"))
        indent()
        addStatement("text = %S,", param.label)
        add("style = %M.typography.labelSmall,\n",
            MemberName("androidx.compose.material3", "MaterialTheme"))
        add("modifier = %T.%M().%M(top = 8.%M),\n",
            modifierClass, fillMaxWidthMember, paddingMember, dpMember)
        unindent()
        add(")\n")
        for (subParam in param.dataClassParams) {
            val namespacedParam = subParam.copy(name = "${param.name}.${subParam.name}")
            add(buildWidgetCall(namespacedParam))
        }
    }

    // ── sealed class ──────────────────────────────────────────────────────────

    private fun buildSealedClassSection(param: ParamModel): CodeBlock {
        val variantKey = "${param.name}#variant"
        val defaultVariant = param.defaultValue.ifEmpty {
            param.sealedSubtypes.firstOrNull()?.name ?: ""
        }
        val variantNames = param.sealedSubtypes.map { it.name }
        return buildCodeBlock {
            // Variant dropdown
            add("%M(\n", MemberName(WIDGETS_PACKAGE, "PreviewDropdownField"))
            indent()
            addStatement("label = %S,", "${param.label} (type)")
            add("value = state[%S] ?: %S,\n", variantKey, defaultVariant)
            add("options = listOf(")
            variantNames.forEachIndexed { i, v -> if (i > 0) add(", "); add("%S", v) }
            add("),\n")
            add("onValue = { onUpdate(state.put(%S, it)) },\n", variantKey)
            unindent()
            add(")\n")
            // Per-variant fields
            if (param.sealedSubtypes.any { !it.isObject && it.params.isNotEmpty() }) {
                add("when (state[%S] ?: %S) {\n", variantKey, defaultVariant)
                indent()
                for (subtype in param.sealedSubtypes) {
                    if (!subtype.isObject && subtype.params.isNotEmpty()) {
                        add("%S -> {\n", subtype.name)
                        indent()
                        for (subParam in subtype.params) {
                            val key = "${param.name}.${subtype.name}.${subParam.name}"
                            add(buildWidgetCall(subParam.copy(name = key)))
                        }
                        unindent()
                        add("}\n")
                    }
                }
                unindent()
                add("}\n")
            }
        }
    }

    // ── typed primitives ──────────────────────────────────────────────────────

    private fun buildTypedFieldCall(param: ParamModel): CodeBlock = when (param.kotlinType) {
        "kotlin.String"  -> buildFieldCall("PreviewStringField", param, CodeBlock.of("%S", param.defaultValue))
        "kotlin.Boolean" -> buildFieldCall("PreviewBooleanField", param,
            CodeBlock.of("%L", if (param.defaultValue == "true") "true" else "false"))
        "kotlin.Int",
        "kotlin.Long"    -> buildFieldCall("PreviewIntField", param,
            CodeBlock.of("%L", param.defaultValue.toIntOrNull() ?: 0))
        "kotlin.Float",
        "kotlin.Double"  -> buildFieldCall("PreviewFloatField", param,
            CodeBlock.of("%L", "${param.defaultValue.toFloatOrNull() ?: 0.0f}f"))
        "androidx.compose.ui.graphics.Color" -> buildColorCall(param)
        "androidx.compose.ui.unit.Dp"        -> buildDpCall(param)
        "androidx.compose.ui.unit.TextUnit"  -> buildTextUnitCall(param)
        else             -> buildCustomTypeCall(param)
    }

    private fun buildCustomTypeCall(param: ParamModel): CodeBlock = buildCodeBlock {
        add("%M(\n", MemberName(WIDGETS_PACKAGE, "PreviewCustomTypeField"))
        indent()
        addStatement("label = %S,", param.label)
        addStatement("kotlinType = %S,", param.kotlinType)
        addStatement("stateKey = %S,", param.name)
        add("state = state,\n")
        add("onUpdate = onUpdate,\n")
        if (param.description.isNotEmpty()) addStatement("description = %S,", param.description)
        unindent()
        add(")\n")
    }

    private fun buildFieldCall(widgetName: String, param: ParamModel, defaultLiteral: CodeBlock): CodeBlock =
        buildCodeBlock {
            add("%M(\n", MemberName(WIDGETS_PACKAGE, widgetName))
            indent()
            addStatement("label = %S,", param.label)
            add("value = state[%S] ?: %L,\n", param.name, defaultLiteral)
            addStatement("onValue = { onUpdate(state.put(%S, it)) },", param.name)
            if (param.description.isNotEmpty()) addStatement("description = %S,", param.description)
            unindent()
            add(")\n")
        }

    private fun buildDropdownCall(param: ParamModel): CodeBlock {
        val options = param.options.ifEmpty { param.enumValues }
        val defaultLiteral = CodeBlock.of("%S", param.defaultValue.ifEmpty { options.firstOrNull() ?: "" })
        return buildCodeBlock {
            add("%M(\n", MemberName(WIDGETS_PACKAGE, "PreviewDropdownField"))
            indent()
            addStatement("label = %S,", param.label)
            add("value = state[%S] ?: %L,\n", param.name, defaultLiteral)
            add("options = listOf(")
            options.forEachIndexed { i, opt -> if (i > 0) add(", "); add("%S", opt) }
            add("),\n")
            addStatement("onValue = { onUpdate(state.put(%S, it)) },", param.name)
            if (param.description.isNotEmpty()) addStatement("description = %S,", param.description)
            unindent()
            add(")\n")
        }
    }

    private fun buildColorCall(param: ParamModel): CodeBlock {
        val defaultLiteral = param.defaultValue.toLongOrNull()?.let { value ->
            CodeBlock.of("%T(%LL.toInt())", colorClass, value)
        } ?: CodeBlock.of("%T.%L", colorClass, "Unspecified")
        return buildFieldCall("PreviewColorField", param, defaultLiteral)
    }

    private fun buildDpCall(param: ParamModel): CodeBlock {
        val floatVal = param.defaultValue.toFloatOrNull() ?: 0f
        val defaultLiteral = CodeBlock.of("%T(%Lf)", dpClass, floatVal)
        return buildFieldCall("PreviewDpField", param, defaultLiteral)
    }

    private fun buildTextUnitCall(param: ParamModel): CodeBlock {
        val floatVal = param.defaultValue.toFloatOrNull() ?: 16f
        val defaultLiteral = CodeBlock.of("%T(%Lf, %T.%L)", textUnitClass, floatVal, textUnitTypeClass, "Sp")
        return buildFieldCall("PreviewTextUnitField", param, defaultLiteral)
    }
}
