package tech.lucam.composeum.ksp.codegen

import tech.lucam.composeum.ksp.model.ParamModel
import tech.lucam.composeum.ksp.model.PreviewModel
import tech.lucam.composeum.ksp.model.SealedSubtype
import com.google.devtools.ksp.processing.CodeGenerator
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.buildCodeBlock
import com.squareup.kotlinpoet.ksp.writeTo

internal object RegistryGenerator {

    private val previewGroupClass = ClassName("tech.lucam.composeum.annotation", "PreviewGroup")
    private val previewEntryClass = ClassName("tech.lucam.composeum.runtime", "PreviewEntry")
    private val previewRegistryClass = ClassName("tech.lucam.composeum.runtime", "PreviewRegistry")
    private val previewParamDefaultsClass = ClassName("tech.lucam.composeum.runtime", "PreviewParamDefaults")
    private val localPreviewParamStateClass =
        ClassName("tech.lucam.composeum.runtime.ui.component", "LocalPreviewParamState")
    private val colorClass = ClassName("androidx.compose.ui.graphics", "Color")
    private val dpClass = ClassName("androidx.compose.ui.unit", "Dp")
    private val textUnitClass = ClassName("androidx.compose.ui.unit", "TextUnit")
    private val textUnitTypeClass = ClassName("androidx.compose.ui.unit", "TextUnitType")
    private val listClass = ClassName("kotlin.collections", "List")
    private val androidViewMember = MemberName("androidx.compose.ui.viewinterop", "AndroidView")

    private val knownTypes = setOf(
        "kotlin.String", "kotlin.Boolean", "kotlin.Int", "kotlin.Long",
        "kotlin.Float", "kotlin.Double",
        "androidx.compose.ui.graphics.Color",
        "androidx.compose.ui.unit.Dp",
        "androidx.compose.ui.unit.TextUnit",
    )

    fun generate(
        models: List<PreviewModel>,
        codeGenerator: CodeGenerator,
        registryPackage: String,
        registryName: String,
    ) {
        val fileBuilder = FileSpec.builder(registryPackage, registryName)
            .addFileComment("DO NOT EDIT — generated by compose-preview KSP processor")

        // Import the top-level class of each group expression (e.g. "AppGroup" for "AppGroup.Components").
        // Android preview models have groupImport="" so the lastDot check filters them out naturally.
        for (model in models) {
            val lastDot = model.groupImport.lastIndexOf('.')
            if (lastDot >= 0) {
                fileBuilder.addImport(
                    model.groupImport.substring(0, lastDot),
                    model.groupImport.substring(lastDot + 1),
                )
            }
        }

        // Emit one private synthetic PreviewGroup object per unique generated group string.
        val syntheticGroups = models
            .mapNotNull { model ->
                model.syntheticGroupDisplayName?.let { model.groupExpression to it }
            }
            .toMap()
        for ((objectName, displayName) in syntheticGroups) {
            fileBuilder.addType(
                TypeSpec.objectBuilder(objectName)
                    .addModifiers(KModifier.PRIVATE)
                    .addSuperinterface(previewGroupClass)
                    .addProperty(
                        PropertySpec.builder("name", String::class, KModifier.OVERRIDE)
                            .initializer("%S", displayName)
                            .build()
                    )
                    .build()
            )
        }

        val listType = listClass.parameterizedBy(previewEntryClass)

        val objectSpec = TypeSpec.objectBuilder(registryName)
            .addSuperinterface(previewRegistryClass)
            .addProperty(
                PropertySpec.builder("entries", listType, KModifier.OVERRIDE)
                    .initializer(buildEntriesCodeBlock(models))
                    .build()
            )
            .build()

        fileBuilder.addType(objectSpec)
        fileBuilder.build().writeTo(codeGenerator, aggregating = true)
    }

    private fun buildEntriesCodeBlock(models: List<PreviewModel>): CodeBlock = buildCodeBlock {
        add("listOf(\n")
        indent()
        for (model in models) {
            add(buildEntryCodeBlock(model))
            add(",\n")
        }
        unindent()
        add(")")
    }

    private fun buildEntryCodeBlock(model: PreviewModel): CodeBlock {
        val functionMember = MemberName(model.functionPackage, model.functionSimpleName)
        return buildCodeBlock {
            add("%T(\n", previewEntryClass)
            indent()
            addStatement("key = %S,", model.key)
            addStatement("name = %S,", model.name)
            addStatement("group = %L,", model.groupExpression)
            addStatement("description = %S,", model.description)
            if (model.tags.isEmpty()) {
                addStatement("tags = emptyList(),")
            } else {
                add("tags = listOf(")
                model.tags.forEachIndexed { i, tag ->
                    if (i > 0) add(", ")
                    add("%S", tag)
                }
                add("),\n")
            }
            add(
                "composable = %L,\n",
                buildComposableLambda(functionMember, model.params, model.isViewPreview, model.hasContextParam),
            )
            if (model.params.isEmpty()) {
                addStatement("paramForm = null,")
                addStatement(
                    "paramDefaults = %T(defaults = emptyMap()),",
                    previewParamDefaultsClass,
                )
            } else {
                val formName = "${model.functionSimpleName}ParamForm"
                addStatement(
                    "paramForm = { state, onUpdate -> %L(state, onUpdate) },",
                    formName,
                )
                add("paramDefaults = %T(\n", previewParamDefaultsClass)
                indent()
                add("defaults = mapOf(\n")
                indent()
                for (param in model.params) {
                    for ((key, value) in expandDefaults(param)) {
                        add("%S to %L,\n", key, value)
                    }
                }
                unindent()
                add("),\n")
                unindent()
                add("),\n")
                // Map custom-type param state keys to their FQN so PreviewDetailScreen can seed
                // the initial state with runtime-provided CustomParamField.initialValue values.
                val customKeys = collectCustomTypeParamKeys(model.params)
                if (customKeys.isEmpty()) {
                    addStatement("customTypeParamKeys = emptyMap(),")
                } else {
                    add("customTypeParamKeys = mapOf(\n")
                    indent()
                    for ((key, type) in customKeys) {
                        addStatement("%S to %S,", key, type)
                    }
                    unindent()
                    add("),\n")
                }
            }
            addStatement("sourceFile = %S,", model.sourceFile)
            addStatement("sourceLine = %L,", model.sourceLine)
            unindent()
            add(")")
        }
    }

    /**
     * Expands a [ParamModel] into one or more (state-key, default-value-literal) pairs.
     * Data class, sealed, list, and nullable params expand to multiple keys.
     */
    private fun expandDefaults(param: ParamModel): List<Pair<String, CodeBlock>> = when {
        param.isNullable -> {
            val isNullDefault = param.defaultValue.isEmpty() || param.defaultValue == "null"
            listOf("${param.name}#isNull" to CodeBlock.of("%L", isNullDefault)) +
                expandDefaults(param.copy(isNullable = false))
        }
        param.isDataClass -> {
            param.dataClassParams.flatMap { subParam ->
                expandDefaults(subParam.copy(name = "${param.name}.${subParam.name}"))
            }
        }
        param.isSealedClass -> {
            val defaultVariant = param.defaultValue.ifEmpty {
                param.sealedSubtypes.firstOrNull()?.name ?: ""
            }
            val variantEntry = listOf("${param.name}#variant" to CodeBlock.of("%S", defaultVariant))
            val subEntries = param.sealedSubtypes.flatMap { subtype ->
                subtype.params.flatMap { subParam ->
                    expandDefaults(subParam.copy(name = "${param.name}.${subtype.name}.${subParam.name}"))
                }
            }
            variantEntry + subEntries
        }
        param.isList -> {
            val rawItems = param.defaultValue.split("|").filter { it.isNotEmpty() }
            val countEntry = listOf("${param.name}#count" to CodeBlock.of("%L", rawItems.size))
            val itemEntries = rawItems.mapIndexed { i, v ->
                "${param.name}#$i" to defaultLiteralForListElement(param.listElementKotlinType, v)
            }
            countEntry + itemEntries
        }
        // Custom types (not a known primitive, enum, or options list): initial value is provided
        // at runtime by CustomParamField.initialValue, so no compile-time default is emitted.
        // withCustomTypeDefaults() in PreviewParamState will seed state before the first render.
        !param.isEnum && param.options.isEmpty() && param.kotlinType !in knownTypes -> emptyList()
        else -> listOf(param.name to defaultValueLiteral(param))
    }

    /** Converts a string-encoded default (from @PreviewParam.default) to a typed Kotlin literal. */
    private fun defaultValueLiteral(param: ParamModel): CodeBlock {
        if (param.isEnum || param.options.isNotEmpty()) return CodeBlock.of("%S", param.defaultValue)
        return defaultLiteralForType(param.kotlinType, param.defaultValue)
    }

    private fun defaultLiteralForType(kotlinType: String, raw: String): CodeBlock = when (kotlinType) {
        "kotlin.Boolean" -> CodeBlock.of("%L", if (raw == "true") "true" else "false")
        "kotlin.Int"     -> CodeBlock.of("%L", raw.toIntOrNull() ?: 0)
        "kotlin.Long"    -> CodeBlock.of("%L", "${raw.toLongOrNull() ?: 0L}L")
        "kotlin.Float"   -> CodeBlock.of("%L", "${raw.toFloatOrNull() ?: 0.0f}f")
        "kotlin.Double"  -> CodeBlock.of("%L", raw.toDoubleOrNull() ?: 0.0)
        "kotlin.String"  -> CodeBlock.of("%S", raw)
        "androidx.compose.ui.graphics.Color" -> colorDefaultLiteral(raw)
        "androidx.compose.ui.unit.Dp" -> {
            val f = raw.toFloatOrNull() ?: 0f
            CodeBlock.of("%T(%Lf)", dpClass, f)
        }
        "androidx.compose.ui.unit.TextUnit" -> {
            val f = raw.toFloatOrNull() ?: 16f
            CodeBlock.of("%T(%Lf, %T.%L)", textUnitClass, f, textUnitTypeClass, "Sp")
        }
        else -> CodeBlock.of("%S", raw)
    }

    private fun defaultLiteralForListElement(kotlinType: String, raw: String): CodeBlock =
        defaultLiteralForType(kotlinType, raw)

    /**
     * Recursively collects (stateKey → kotlinTypeFQN) pairs for all params that fall through
     * to the custom-type handler (not a known primitive, enum, list, data class, or sealed type).
     * These keys need runtime-provided [tech.lucam.composeum.runtime.config.CustomParamField.initialValue]
     * from [tech.lucam.composeum.runtime.config.PreviewConfig.customTypeFields].
     */
    private fun collectCustomTypeParamKeys(params: List<ParamModel>): Map<String, String> {
        val result = mutableMapOf<String, String>()
        for (param in params) collectCustomKeys(param, result)
        return result
    }

    private fun collectCustomKeys(param: ParamModel, result: MutableMap<String, String>) {
        when {
            param.isNullable -> collectCustomKeys(param.copy(isNullable = false), result)
            param.isDataClass -> param.dataClassParams.forEach {
                collectCustomKeys(it.copy(name = "${param.name}.${it.name}"), result)
            }
            param.isSealedClass -> param.sealedSubtypes.forEach { subtype ->
                subtype.params.forEach { sub ->
                    collectCustomKeys(
                        sub.copy(name = "${param.name}.${subtype.name}.${sub.name}"),
                        result,
                    )
                }
            }
            param.isList || param.isEnum || param.options.isNotEmpty() -> {}
            param.kotlinType in knownTypes -> {}
            else -> result[param.name] = param.kotlinType
        }
    }

    private fun colorDefaultLiteral(raw: String): CodeBlock =
        raw.toLongOrNull()?.let { value ->
            // value is an ARGB Int stored as Long (e.g. 0xFF0000FF = 4278190335).
            // Color(Int) is the correct constructor for ARGB values; Color(ULong) would
            // interpret the bits as a raw 64-bit color representation (different encoding).
            CodeBlock.of("%T(%LL.toInt())", colorClass, value)
        } ?: CodeBlock.of("%T.%L", colorClass, "Unspecified")

    /**
     * Builds the composable lambda for a registry entry.
     *
     * - For `@ViewPreview` functions the lambda wraps the call in `AndroidView { factory = ... }`.
     * - For `@ComposePreview` with no params the lambda is simply `{ FunctionName() }`.
     * - For `@ComposePreview` with params the lambda reads [LocalPreviewParamState] and
     *   passes each param as a typed named argument so that widget changes are reflected.
     */
    private fun buildComposableLambda(
        functionMember: MemberName,
        params: List<ParamModel>,
        isViewPreview: Boolean,
        hasContextParam: Boolean,
    ): CodeBlock {
        if (isViewPreview) {
            return if (hasContextParam) {
                buildCodeBlock { add("{ %M(factory = { %M(it) }) }", androidViewMember, functionMember) }
            } else {
                buildCodeBlock { add("{ %M(factory = { %M() }) }", androidViewMember, functionMember) }
            }
        }
        if (params.isEmpty()) {
            return buildCodeBlock { add("{ %M() }", functionMember) }
        }
        return buildCodeBlock {
            add("{\n")
            indent()
            add("val _state = %T.current\n", localPreviewParamStateClass)
            add("%M(\n", functionMember)
            indent()
            for (param in params) {
                add("%L = %L,\n", param.name, buildParamRead(param))
            }
            unindent()
            add(")\n")
            unindent()
            add("}")
        }
    }

    /** Builds the expression that reads one top-level param from _state with the correct type. */
    private fun buildParamRead(param: ParamModel): CodeBlock = when {
        param.isNullable -> buildNullableRead(param)
        param.isDataClass -> buildDataClassRead(param)
        param.isSealedClass -> buildSealedClassRead(param)
        param.isList -> buildListRead(param)
        param.isEnum -> {
            val enumClass = ClassName.bestGuess(param.kotlinType)
            val default = param.defaultValue.ifEmpty { param.enumValues.firstOrNull() ?: "" }
            buildCodeBlock {
                add("%T.valueOf(_state.get<String>(%S) ?: %S)", enumClass, param.name, default)
            }
        }
        param.options.isNotEmpty() -> {
            val default = param.defaultValue.ifEmpty { param.options.firstOrNull() ?: "" }
            buildCodeBlock { add("_state.get<String>(%S) ?: %S", param.name, default) }
        }
        else -> buildTypedRead(param.name, param.kotlinType, param.defaultValue)
    }

    private fun buildNullableRead(param: ParamModel): CodeBlock {
        val isNullKey = "${param.name}#isNull"
        val defaultIsNull = param.defaultValue.isEmpty() || param.defaultValue == "null"
        val innerRead = buildParamRead(param.copy(isNullable = false))
        return buildCodeBlock {
            add("if (_state.get<Boolean>(%S) ?: %L) null else %L",
                isNullKey, defaultIsNull, innerRead)
        }
    }

    private fun buildDataClassRead(param: ParamModel): CodeBlock {
        val dataClass = ClassName.bestGuess(param.kotlinType)
        return buildCodeBlock {
            add("%T(\n", dataClass)
            indent()
            for (subParam in param.dataClassParams) {
                val namespacedParam = subParam.copy(name = "${param.name}.${subParam.name}")
                add("%L = %L,\n", subParam.name, buildParamRead(namespacedParam))
            }
            unindent()
            add(")")
        }
    }

    private fun buildSealedClassRead(param: ParamModel): CodeBlock {
        val sealedClass = ClassName.bestGuess(param.kotlinType)
        val defaultVariant = param.defaultValue.ifEmpty {
            param.sealedSubtypes.firstOrNull()?.name ?: ""
        }
        val defaultSubtype = param.sealedSubtypes.firstOrNull { it.name == defaultVariant }
            ?: param.sealedSubtypes.firstOrNull()
        return buildCodeBlock {
            add("when (_state.get<String>(%S) ?: %S) {\n", "${param.name}#variant", defaultVariant)
            indent()
            for (subtype in param.sealedSubtypes) {
                add("%S -> ", subtype.name)
                add(buildSubtypeConstruction(sealedClass, subtype, param.name))
                add("\n")
            }
            // Fallback: construct the default variant (must be valid, not just a class reference)
            add("else -> ")
            if (defaultSubtype != null) {
                add(buildSubtypeConstruction(sealedClass, defaultSubtype, param.name))
            } else {
                add("error(%S)", "Unknown sealed subtype")
            }
            add("\n")
            unindent()
            add("}")
        }
    }

    private fun buildSubtypeConstruction(
        sealedClass: ClassName,
        subtype: SealedSubtype,
        paramName: String,
    ): CodeBlock = if (subtype.isObject) {
        buildCodeBlock { add("%T.%L", sealedClass, subtype.name) }
    } else {
        buildCodeBlock {
            add("%T.%L(\n", sealedClass, subtype.name)
            indent()
            for (subParam in subtype.params) {
                val key = "$paramName.${subtype.name}.${subParam.name}"
                add("%L = %L,\n", subParam.name, buildParamRead(subParam.copy(name = key)))
            }
            unindent()
            add(")")
        }
    }

    private fun buildListRead(param: ParamModel): CodeBlock {
        val countKey = "${param.name}#count"
        val prefix = "${param.name}#"
        val rawItems = param.defaultValue.split("|").filter { it.isNotEmpty() }
        val defaultCount = rawItems.size
        return buildCodeBlock {
            add("run {\n")
            indent()
            add("val _count = _state.get<Int>(%S) ?: %L\n", countKey, defaultCount)
            add("(0 until _count).map { _i -> %L }\n",
                buildListElementRead(param.listElementKotlinType, prefix))
            unindent()
            add("}")
        }
    }

    private fun buildListElementRead(elementType: String, prefix: String): CodeBlock = when (elementType) {
        "kotlin.String"  -> buildCodeBlock {
            add("_state.get<String>(%S + _i.toString()) ?: %S", prefix, "")
        }
        "kotlin.Int"     -> buildCodeBlock { add("_state.get<Int>(%S + _i.toString()) ?: 0", prefix) }
        "kotlin.Long"    -> buildCodeBlock { add("_state.get<Long>(%S + _i.toString()) ?: 0L", prefix) }
        "kotlin.Float"   -> buildCodeBlock { add("_state.get<Float>(%S + _i.toString()) ?: 0f", prefix) }
        "kotlin.Double"  -> buildCodeBlock { add("_state.get<Double>(%S + _i.toString()) ?: 0.0", prefix) }
        "kotlin.Boolean" -> buildCodeBlock { add("_state.get<Boolean>(%S + _i.toString()) ?: false", prefix) }
        else             -> buildCodeBlock {
            add("_state.get<String>(%S + _i.toString()) ?: %S", prefix, "")
        }
    }

    private fun buildTypedRead(name: String, kotlinType: String, defaultValue: String): CodeBlock =
        when (kotlinType) {
            "kotlin.String"  -> buildCodeBlock { add("_state.get<String>(%S) ?: %S", name, defaultValue) }
            "kotlin.Boolean" -> buildCodeBlock {
                add("_state.get<Boolean>(%S) ?: %L", name,
                    if (defaultValue == "true") "true" else "false")
            }
            "kotlin.Int"     -> buildCodeBlock {
                add("_state.get<Int>(%S) ?: %L", name, defaultValue.toIntOrNull() ?: 0)
            }
            "kotlin.Long"    -> buildCodeBlock {
                add("_state.get<Long>(%S) ?: %L", name, "${defaultValue.toLongOrNull() ?: 0L}L")
            }
            "kotlin.Float"   -> buildCodeBlock {
                add("_state.get<Float>(%S) ?: %L", name, "${defaultValue.toFloatOrNull() ?: 0.0f}f")
            }
            "kotlin.Double"  -> buildCodeBlock {
                add("_state.get<Double>(%S) ?: %L", name, defaultValue.toDoubleOrNull() ?: 0.0)
            }
            "androidx.compose.ui.graphics.Color" -> buildCodeBlock {
                add("_state.get<%T>(%S) ?: %L", colorClass, name, colorDefaultLiteral(defaultValue))
            }
            "androidx.compose.ui.unit.Dp" -> {
                val f = defaultValue.toFloatOrNull() ?: 0f
                buildCodeBlock {
                    add("_state.get<%T>(%S) ?: %T(%Lf)", dpClass, name, dpClass, f)
                }
            }
            "androidx.compose.ui.unit.TextUnit" -> {
                val f = defaultValue.toFloatOrNull() ?: 16f
                buildCodeBlock {
                    add("_state.get<%T>(%S) ?: %T(%Lf, %T.%L)",
                        textUnitClass, name, textUnitClass, f, textUnitTypeClass, "Sp")
                }
            }
            else -> {
                val typeClass = ClassName.bestGuess(kotlinType)
                buildCodeBlock {
                    add(
                        "_state.get<%T>(%S) ?: error(%S)",
                        typeClass, name,
                        "No initial value for custom param '$name' of type '$kotlinType'. " +
                        "Register a customTypeField in PreviewConfig.",
                    )
                }
            }
        }
}
